// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlcgen

import (
	"database/sql"
)

type ApiEndpoint struct {
	ApiEndpointID       int32
	EndpointName        string
	EndpointDescription sql.NullString
}

type ApiUsageSummary struct {
	UsageSummaryID int32
	UsageStartDate int32
	UsageEndDate   int32
	TotalCalls     int32
	TotalCost      float64
	SubscriptionID int32
	ApiEndpointID  int32
	OrganizationID int32
}

type BillingHistory struct {
	BillingID        int32
	BillingStartDate int32
	BillingEndDate   int32
	TotalAmountDue   float64
	TotalCalls       int32
	PaymentStatus    string
	PaymentDate      sql.NullInt32
	BillingCreatedAt int32
	SubscriptionID   int32
}

type CustomEndpointPricing struct {
	CustomEndpointPricingID int32
	CustomCostPerCall       float64
	CustomRateLimit         int32
	SubscriptionID          int32
	TierBasePricingID       int32
}

type Organization struct {
	OrganizationID           int32
	OrganizationName         string
	OrganizationCreatedAt    int32
	OrganizationUpdatedAt    int32
	OrganizationRealm        string
	OrganizationCountry      sql.NullString
	OrganizationSupportEmail string
	OrganizationActive       sql.NullBool
	OrganizationReportQ      sql.NullBool
	OrganizationConfig       sql.NullString
	OrganizationTypeID       int32
}

type OrganizationPermission struct {
	OrganizationPermissionID int32
	ResourceTypeID           int32
	PermissionCode           string
	OrganizationID           int32
}

type OrganizationType struct {
	OrganizationTypeID   int32
	OrganizationTypeName string
}

type ResourceType struct {
	ResourceTypeID          int32
	ResourceTypeCode        string
	ResourceTypeName        string
	ResourceTypeDescription sql.NullString
}

type Subscription struct {
	SubscriptionID          int32
	SubscriptionName        string
	SubscriptionType        string
	SubscriptionCreatedDate int32
	SubscriptionUpdatedDate int32
	SubscriptionStartDate   int32
	SubscriptionApiLimit    sql.NullInt32
	SubscriptionExpiryDate  sql.NullInt32
	SubscriptionDescription sql.NullString
	SubscriptionStatus      sql.NullBool
	OrganizationID          int32
	SubscriptionTierID      int32
}

type SubscriptionTier struct {
	SubscriptionTierID int32
	TierName           string
	TierArchived       bool
	TierDescription    sql.NullString
	TierCreatedAt      int32
	TierUpdatedAt      int32
}

type TierBasePricing struct {
	TierBasePricingID  int32
	BaseCostPerCall    float64
	BaseRateLimit      sql.NullInt32
	ApiEndpointID      int32
	SubscriptionTierID int32
}
