// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: org_type.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createOrgType = `-- name: CreateOrgType :execresult
INSERT INTO organization_type (organization_type_name) 
VALUES (?)
`

func (q *Queries) CreateOrgType(ctx context.Context, organizationTypeName string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrgType, organizationTypeName)
}

const createOrgTypes = `-- name: CreateOrgTypes :copyfrom
INSERT INTO organization_type (organization_type_name) 
VALUES (?)
`

const deleteOrgTypeById = `-- name: DeleteOrgTypeById :exec
DELETE FROM organization_type
WHERE organization_type_id = ?
`

func (q *Queries) DeleteOrgTypeById(ctx context.Context, organizationTypeID int32) error {
	_, err := q.db.ExecContext(ctx, deleteOrgTypeById, organizationTypeID)
	return err
}

const listOrgType = `-- name: ListOrgType :many
SELECT organization_type_id, organization_type_name FROM organization_type
ORDER BY organization_type_name
LIMIT ? OFFSET ?
`

type ListOrgTypeParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrgType(ctx context.Context, arg ListOrgTypeParams) ([]OrganizationType, error) {
	rows, err := q.db.QueryContext(ctx, listOrgType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationType{}
	for rows.Next() {
		var i OrganizationType
		if err := rows.Scan(&i.OrganizationTypeID, &i.OrganizationTypeName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
