// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: tier_pricing.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createTierPricing = `-- name: CreateTierPricing :execresult
INSERT INTO tier_base_pricing (subscription_tier_id, api_endpoint_id, base_cost_per_call, base_rate_limit) 
VALUES (?, ?, ?, ?)
`

type CreateTierPricingParams struct {
	SubscriptionTierID int32
	ApiEndpointID      int32
	BaseCostPerCall    float64
	BaseRateLimit      sql.NullInt32
}

func (q *Queries) CreateTierPricing(ctx context.Context, arg CreateTierPricingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTierPricing,
		arg.SubscriptionTierID,
		arg.ApiEndpointID,
		arg.BaseCostPerCall,
		arg.BaseRateLimit,
	)
}

const deleteTierPricingById = `-- name: DeleteTierPricingById :exec
DELETE FROM tier_base_pricing
WHERE tier_base_pricing_id = ?
`

func (q *Queries) DeleteTierPricingById(ctx context.Context, tierBasePricingID int32) error {
	_, err := q.db.ExecContext(ctx, deleteTierPricingById, tierBasePricingID)
	return err
}

const deleteTierPricingByTierId = `-- name: DeleteTierPricingByTierId :exec
DELETE FROM tier_base_pricing
WHERE subscription_tier_id = ?
`

func (q *Queries) DeleteTierPricingByTierId(ctx context.Context, subscriptionTierID int32) error {
	_, err := q.db.ExecContext(ctx, deleteTierPricingByTierId, subscriptionTierID)
	return err
}

const getTierPricingByTierId = `-- name: GetTierPricingByTierId :many

SELECT tier_base_pricing_id, base_cost_per_call, base_rate_limit, api_endpoint_id, subscription_tier_id FROM tier_base_pricing
WHERE subscription_tier_id = ?
`

// -- name: ListTierPricing :many
// SELECT * FROM tier_base_pricing
// ORDER BY subscription_tier_id;
func (q *Queries) GetTierPricingByTierId(ctx context.Context, subscriptionTierID int32) ([]TierBasePricing, error) {
	rows, err := q.db.QueryContext(ctx, getTierPricingByTierId, subscriptionTierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TierBasePricing
	for rows.Next() {
		var i TierBasePricing
		if err := rows.Scan(
			&i.TierBasePricingID,
			&i.BaseCostPerCall,
			&i.BaseRateLimit,
			&i.ApiEndpointID,
			&i.SubscriptionTierID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTierPricingById = `-- name: UpdateTierPricingById :execresult
UPDATE tier_base_pricing
SET 
    base_cost_per_call = ?,
    base_rate_limit = ?,
    api_endpoint_id = ?
WHERE tier_base_pricing_id = ?
`

type UpdateTierPricingByIdParams struct {
	BaseCostPerCall   float64
	BaseRateLimit     sql.NullInt32
	ApiEndpointID     int32
	TierBasePricingID int32
}

func (q *Queries) UpdateTierPricingById(ctx context.Context, arg UpdateTierPricingByIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTierPricingById,
		arg.BaseCostPerCall,
		arg.BaseRateLimit,
		arg.ApiEndpointID,
		arg.TierBasePricingID,
	)
}

const updateTierPricingByTierId = `-- name: UpdateTierPricingByTierId :execresult
UPDATE tier_base_pricing
SET 
    base_cost_per_call = ?,
    base_rate_limit = ?,
    api_endpoint_id = ?
WHERE subscription_tier_id = ?
`

type UpdateTierPricingByTierIdParams struct {
	BaseCostPerCall    float64
	BaseRateLimit      sql.NullInt32
	ApiEndpointID      int32
	SubscriptionTierID int32
}

func (q *Queries) UpdateTierPricingByTierId(ctx context.Context, arg UpdateTierPricingByTierIdParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTierPricingByTierId,
		arg.BaseCostPerCall,
		arg.BaseRateLimit,
		arg.ApiEndpointID,
		arg.SubscriptionTierID,
	)
}
